String.prototype.includes||(String.prototype.includes=function(){return-1!==String.prototype.indexOf.apply(this,arguments)}(function(){function n(a){"string"!==typeof a&&(a=String(a));if(/[^a-z0-9\-#$%&'*+.\^_`|~]/i.test(a))throw new TypeError("Invalid character in header field name");return a.toLowerCase()}function D(a){"string"!==typeof a&&(a=String(a));return a}function f(a){this.map={};a instanceof f?a.forEach(function(a,k){this.append(k,a)},this):a&&Object.getOwnPropertyNames(a).forEach(function(b){this.append(b,
a[b])},this)}function A(a){if(a.bodyUsed)return Promise.reject(new TypeError("Already read"));a.bodyUsed=!0}function E(a){return new Promise(function(b,k){a.onload=function(){b(a.result)};a.onerror=function(){k(a.error)}})}function F(a){var b=new FileReader;b.readAsArrayBuffer(a);return E(b)}function p(){this.bodyUsed=!1;this._initBody=function(a){this._bodyInit=a;if("string"===typeof a)this._bodyText=a;else if(r.blob&&Blob.prototype.isPrototypeOf(a))this._bodyBlob=a;else if(r.formData&&FormData.prototype.isPrototypeOf(a))this._bodyFormData=
a;else if(!a)this._bodyText="";else if(!r.arrayBuffer||!ArrayBuffer.prototype.isPrototypeOf(a))throw Error("unsupported BodyInit type");};r.blob?(this.blob=function(){var a=A(this);if(a)return a;if(this._bodyBlob)return Promise.resolve(this._bodyBlob);if(this._bodyFormData)throw Error("could not read FormData body as blob");return Promise.resolve(new Blob([this._bodyText]))},this.arrayBuffer=function(){return this.blob().then(F)},this.text=function(){var a=A(this);if(a)return a;if(this._bodyBlob){var a=
this._bodyBlob,b=new FileReader;b.readAsText(a);return E(b)}if(this._bodyFormData)throw Error("could not read FormData body as text");return Promise.resolve(this._bodyText)}):this.text=function(){var a=A(this);return a?a:Promise.resolve(this._bodyText)};r.formData&&(this.formData=function(){return this.text().then(t)});this.json=function(){return this.text().then(JSON.parse)};return this}function q(a,b){b=b||{};var k=b.body;if(q.prototype.isPrototypeOf(a)){if(a.bodyUsed)throw new TypeError("Already read");
this.url=a.url;this.credentials=a.credentials;b.headers||(this.headers=new f(a.headers));this.method=a.method;this.mode=a.mode;k||(k=a._bodyInit,a.bodyUsed=!0)}else this.url=a;this.credentials=b.credentials||this.credentials||"omit";if(b.headers||!this.headers)this.headers=new f(b.headers);var B=b.method||this.method||"GET",d=B.toUpperCase();this.method=-1<g.indexOf(d)?d:B;this.mode=b.mode||this.mode||null;this.referrer=null;if(("GET"===this.method||"HEAD"===this.method)&&k)throw new TypeError("Body not allowed for GET or HEAD requests");
this._initBody(k)}function t(a){var b=new FormData;a.trim().split("&").forEach(function(a){if(a){var d=a.split("=");a=d.shift().replace(/\+/g," ");d=d.join("=").replace(/\+/g," ");b.append(decodeURIComponent(a),decodeURIComponent(d))}});return b}function I(a){var b=new f;a.getAllResponseHeaders().trim().split("\n").forEach(function(a){var d=a.trim().split(":");a=d.shift().trim();d=d.join(":").trim();b.append(a,d)});return b}function m(a,b){b||(b={});this._initBody(a);this.type="default";this.status=
b.status;this.ok=200<=this.status&&300>this.status;this.statusText=b.statusText;this.headers=b.headers instanceof f?b.headers:new f(b.headers);this.url=b.url||""}if(!self.fetch){f.prototype.append=function(a,b){a=n(a);b=D(b);var d=this.map[a];d||(d=[],this.map[a]=d);d.push(b)};f.prototype["delete"]=function(a){delete this.map[n(a)]};f.prototype.get=function(a){return(a=this.map[n(a)])?a[0]:null};f.prototype.getAll=function(a){return this.map[n(a)]||[]};f.prototype.has=function(a){return this.map.hasOwnProperty(n(a))};
f.prototype.set=function(a,b){this.map[n(a)]=[D(b)]};f.prototype.forEach=function(a,b){Object.getOwnPropertyNames(this.map).forEach(function(d){this.map[d].forEach(function(f){a.call(b,f,d,this)},this)},this)};var y;if(y="FileReader"in self&&"Blob"in self)try{new Blob,y=!0}catch(v){y=!1}var r={blob:y,formData:"FormData"in self,arrayBuffer:"ArrayBuffer"in self},g="DELETE GET HEAD OPTIONS POST PUT".split(" ");q.prototype.clone=function(){return new q(this)};p.call(q.prototype);p.call(m.prototype);m.prototype.clone=
function(){return new m(this._bodyInit,{status:this.status,statusText:this.statusText,headers:new f(this.headers),url:this.url})};m.error=function(){var a=new m(null,{status:0,statusText:""});a.type="error";return a};var d=[301,302,303,307,308];m.redirect=function(a,b){if(-1===d.indexOf(b))throw new RangeError("Invalid status code");return new m(null,{status:b,headers:{location:a}})};self.Headers=f;self.Request=q;self.Response=m;self.fetch=function(a,b){return new Promise(function(d,f){var g;g=q.prototype.isPrototypeOf(a)&&
!b?a:new q(a,b);var c=new XMLHttpRequest;c.onload=function(){var a=1223===c.status?204:c.status;if(100>a||599<a)f(new TypeError("Network request failed"));else{var b=c.statusText,g=I(c),n;n="responseURL"in c?c.responseURL:/^X-Request-URL:/m.test(c.getAllResponseHeaders())?c.getResponseHeader("X-Request-URL"):void 0;d(new m("response"in c?c.response:c.responseText,{status:a,statusText:b,headers:g,url:n}))}};c.onerror=function(){f(new TypeError("Network request failed"))};c.open(g.method,g.url,!0);
"include"===g.credentials&&(c.withCredentials=!0);"responseType"in c&&r.blob&&(c.responseType="blob");g.headers.forEach(function(a,b){c.setRequestHeader(b,a)});c.send("undefined"===typeof g._bodyInit?null:g._bodyInit)})};self.fetch.polyfill=!0}})());
(function(){function n(e){return"function"===typeof e}function D(){return function(){process.nextTick(p)}}function f(){return function(){O(p)}}function A(){var e=0,a=new P(p),b=document.createTextNode("");a.observe(b,{characterData:!0});return function(){b.data=e=++e%2}}function E(){var e=new MessageChannel;e.port1.onmessage=p;return function(){e.port2.postMessage(0)}}function F(){return function(){setTimeout(p,1)}}function p(){for(var e=0;e<w;e+=2)(0,z[e])(z[e+1]),z[e]=void 0,z[e+1]=void 0;w=0}function q(){try{var e=
require("vertx");O=e.runOnLoop||e.runOnContext;return f()}catch(a){return F()}}function t(){}function I(e,a,b,u){try{e.call(a,b,u)}catch(d){return d}}function m(e,a,b){x(function(e){var c=!1,h=I(b,a,function(b){c||(c=!0,a!==b?v(e,b):g(e,b))},function(a){c||(c=!0,d(e,a))},"Settle: "+(e._label||" unknown promise"));!c&&h&&(c=!0,d(e,h))},e)}function y(e,b){1===b._state?g(e,b._result):2===b._state?d(e,b._result):a(b,void 0,function(a){v(e,a)},function(a){d(e,a)})}function v(e,a){if(e===a)d(e,new TypeError("You cannot resolve a promise with itself"));
else if("function"===typeof a||"object"===typeof a&&null!==a)if(a.constructor===e.constructor)y(e,a);else{var b;try{b=a.then}catch(u){G.error=u,b=G}b===G?d(e,G.error):void 0===b?g(e,a):n(b)?m(e,a,b):g(e,a)}else g(e,a)}function r(a){a._onerror&&a._onerror(a._result);b(a)}function g(a,J){void 0===a._state&&(a._result=J,a._state=1,0!==a._subscribers.length&&x(b,a))}function d(a,b){void 0===a._state&&(a._state=2,a._result=b,x(r,a))}function a(a,J,d,u){var c=a._subscribers,h=c.length;a._onerror=null;c[h]=
J;c[h+1]=d;c[h+2]=u;0===h&&a._state&&x(b,a)}function b(a){var b=a._subscribers,d=a._state;if(0!==b.length){for(var c,f,h=a._result,g=0;g<b.length;g+=3)c=b[g],f=b[g+d],c?B(d,c,f,h):f(h);a._subscribers.length=0}}function k(){this.error=null}function B(a,b,c,u){var f=n(c),h,l,k,m;if(f){try{h=c(u)}catch(p){K.error=p,h=K}h===K?(m=!0,l=h.error,h=null):k=!0;if(b===h){d(b,new TypeError("A promises callback cannot return that same promise."));return}}else h=u,k=!0;void 0===b._state&&(f&&k?v(b,h):m?d(b,l):
1===a?g(b,h):2===a&&d(b,h))}function R(a,b){try{b(function(b){v(a,b)},function(b){d(a,b)})}catch(c){d(a,c)}}function c(a,b){this._instanceConstructor=a;this.promise=new a(t);this._validateInput(b)?(this._input=b,this._remaining=this.length=b.length,this._init(),0===this.length?g(this.promise,this._result):(this.length=this.length||0,this._enumerate(),0===this._remaining&&g(this.promise,this._result))):d(this.promise,this._validationError())}function l(a){this._id=S++;this._result=this._state=void 0;
this._subscribers=[];if(t!==a){if(!n(a))throw new TypeError("You must pass a resolver function as the first argument to the promise constructor");if(!(this instanceof l))throw new TypeError("Failed to construct 'Promise': Please use the 'new' operator, this object constructor cannot be called as a function.");R(this,a)}}var N=Array.isArray?Array.isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},w=0,O,L,x=function(a,b){z[w]=a;z[w+1]=b;w+=2;2===w&&(L?L(p):Q())},C="undefined"!==
typeof window?window:void 0,H=C||{},P=H.MutationObserver||H.WebKitMutationObserver,H="undefined"!==typeof process&&"[object process]"==={}.toString.call(process),T="undefined"!==typeof Uint8ClampedArray&&"undefined"!==typeof importScripts&&"undefined"!==typeof MessageChannel,z=Array(1E3),Q;Q=H?D():P?A():T?E():void 0===C&&"function"===typeof require?q():F();var G=new k,K=new k;c.prototype._validateInput=function(a){return N(a)};c.prototype._validationError=function(){return Error("Array Methods must be provided an Array")};
c.prototype._init=function(){this._result=Array(this.length)};c.prototype._enumerate=function(){for(var a=this.length,b=this.promise,c=this._input,d=0;void 0===b._state&&d<a;d++)this._eachEntry(c[d],d)};c.prototype._eachEntry=function(a,b){var d=this._instanceConstructor;"object"===typeof a&&null!==a?a.constructor===d&&void 0!==a._state?(a._onerror=null,this._settledAt(a._state,b,a._result)):this._willSettleAt(d.resolve(a),b):(this._remaining--,this._result[b]=a)};c.prototype._settledAt=function(a,
b,c){var f=this.promise;void 0===f._state&&(this._remaining--,2===a?d(f,c):this._result[b]=c);0===this._remaining&&g(f,this._result)};c.prototype._willSettleAt=function(b,d){var c=this;a(b,void 0,function(a){c._settledAt(1,d,a)},function(a){c._settledAt(2,d,a)})};var S=0;l.all=function(a){return(new c(this,a)).promise};l.race=function(b){function c(a){v(g,a)}function f(a){d(g,a)}var g=new this(t);if(!N(b))return d(g,new TypeError("You must pass an array to race.")),g;for(var k=b.length,h=0;void 0===
g._state&&h<k;h++)a(this.resolve(b[h]),void 0,c,f);return g};l.resolve=function(a){if(a&&"object"===typeof a&&a.constructor===this)return a;var b=new this(t);v(b,a);return b};l.reject=function(a){var b=new this(t);d(b,a);return b};l._setScheduler=function(a){L=a};l._setAsap=function(a){x=a};l._asap=x;l.prototype={constructor:l,then:function(b,d){var c=this._state;if(1===c&&!b||2===c&&!d)return this;var f=new this.constructor(t),g=this._result;if(c){var h=arguments[c-1];x(function(){B(c,f,h,g)})}else a(this,
f,b,d);return f},"catch":function(a){return this.then(null,a)}};var C=function(){var a;if("undefined"!==typeof global)a=global;else if("undefined"!==typeof self)a=self;else try{a=Function("return this")()}catch(b){throw Error("polyfill failed because global object is unavailable in this environment");}var c=a.Promise;if(!c||"[object Promise]"!==Object.prototype.toString.call(c.resolve())||c.cast)a.Promise=l},M={Promise:l,polyfill:C};"function"===typeof define&&define.amd?define(function(){return M}):
"undefined"!==typeof module&&module.exports?module.exports=M:"undefined"!==typeof this&&(this.ES6Promise=M);C()}).call(this);
